### ISSUE TITLE
I hope it could have a new c# template which with menu bar and docker together.

### ISSUE THREAD

**Issue by Color-Dark** [bonus630/DockerTemplateX7#1]
I hope it could have a new c# template which with menu bar and docker together. I thought it would be very useful. What's more, is there some files making me find the homologous GUID for all of the items?

**Comment by Color-Dark** [comment]
I hope it could have a new c# template which with main menu bar and docker together which could add a new menu option in the main menu bar and I could add items in the new menu options, and the docker would be shown when I click the item. Could it be realized in the future?
--

**Comment by bonus630** [comment]
> I hope it could have a new c# template which with menu bar and docker together. I thought it would be very useful. What's more, is there some files making me find the homologous GUID for all of the items?
You can explorer the DrawUI.xml file in "<coreldraw installation folder>\Draw\UIConfig\DrawUI.xml"

**Comment by bonus630** [comment]
> ## I hope it could have a new c# template which with main menu bar and docker together which could add a new menu option in the main menu bar and I could add items in the new menu options, and the docker would be shown when I click the item. Could it be realized in the future?

Yes is possible, but first i need resolve this question 

https://community.coreldraw.com/sdk/f/coreldraw-and-corel-designer-api/62626/spinner-property-value-bind-trouble-c-xslt
