### ISSUE TITLE
CorelDRAW Tool Addon crashes

### ISSUE THREAD

**Issue by floriskn** [bonus630/DockerTemplateX7#7]
If I start debugging the template, CorelDRAW crashes. The CorelDRAW Control Addon does work, when I start debugging. I am using CorelDRAW 2021

**Comment by floriskn** [comment]
![Config](https://user-images.githubusercontent.com/48930050/137325249-632f6054-e301-41d5-8382-6d16fb5695a4.png)
The config number in config.xml needs to be the same as the resource value in resources.rct
Now the custom tool doesn't crash CorelDRAW anymore.

**Comment by bonus630** [comment]
thanks you a lot .
