### ISSUE TITLE
xlst to call a function defined in a .dll file

### ISSUE THREAD

**Issue by Marerc** [bonus630/DockerTemplateX7#9]
Hi bounus, in this post (https://community.coreldraw.com/sdk/f/coreldraw-and-corel-designer-api/56765/creating-a-custom-menu-with-a-custom-button-in-corel-x8/272326#272326), you had described the .xslt file to create a button and call a macro function. I was wondering whether there is a way to call a function defined in a .dll file, and what if the .dll file is created using c++ or c#.

**Comment by bonus630** [comment]
MenuItem template is a good startup to that purpose

Demo [https://youtu.be/zu5SDlvKkio](https://youtu.be/zu5SDlvKkio)

**Comment by Marerc** [comment]
![image](https://user-images.githubusercontent.com/14820859/174853602-3528331c-e429-4af8-903e-37b156d2a567.png)
Hello, bonus, thanks for your reply, I had looked throught the code, but then I got confused by codes blocks marked above, three key points are
1. what is the differences with a wrapper and a button? they use different guid.
2. the onclick envent of a button is bind in the block where it is defined?
3. what is the parameters for *Bind, is there any material I can refer to?

**Comment by bonus630** [comment]
you need pay attention in the item type "button" will transform in a native coreldraw button "wpfhost" will load ours dll to memory, we dont will use onclick event in this case and yes the bind is like you said.
No exists documentation about coreldraw bind but works similary to "binding" in wpf.
only this https://community.coreldraw.com/sdk/w/articles/218/creating-ruler-tool-for-coreldraw-or-corel-designer

Binds in coreldraw is designed to use wich c++ IDL.
If you uses a coreldraw bind in a "onInvoke" attribute this will call a method in modelview likes a command in wpf in anothers case will linked to properties.

> ![image](https://github.com/assets/14820859/3528331c-e429-4af8-903e-37b156d2a567) Hello, bonus, thanks for your reply, I had looked throught the code, but then I got confused by codes blocks marked above, three key points are
> 
> 1. what is the differences with a wrapper and a button? they use different guid.
> 2. the onclick envent of a button is bind in the block where it is defined?
> 3. what is the parameters for *Bind, is there any material I can refer to?

**Comment by Marerc** [comment]
Thanks for your useful knowelege. Now I have got more familiar with this UI stuff. But one more question, when I read this page  https://community.coreldraw.com/sdk/w/articles/218/creating-ruler-tool-for-coreldraw-or-corel-designer It says CDR X7 is supported however I am working with CDR X4, and not figure it out yet. Do you know what modification should I made to make this plugin framework works in CDR X4?

**Comment by bonus630** [comment]
Sorry, but i dont can help you in this question, i haves start  my studies in X7
